# Uncomment the next line to define a global platform for your project
platform :ios, ‘8.0’

target 'AssistHonest' do
use_frameworks!
pod 'ReactiveCocoa’, 2.5
pod 'pop'
pod 'Shimmer'
pod 'AFNetworking'
pod 'SDWebImage' 
pod 'YYKit’
pod 'SDCycleScrollView', '~> 1.65'
pod 'Masonry'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'IQKeyboardManager'
pod 'Wonderful', '~> 1.2.0'
pod 'Colours'
pod 'FlatUIKit'
pod 'HYBImageCliped', '~> 2.2.4'
pod 'MJRefresh', '~> 3.1.12'
pod 'TZImagePickerController'
pod 'FCFileManager', '~> 1.0.18'
pod 'hpple', '~> 0.2.0'
pod 'DZNEmptyDataSet'
pod 'FCAlertView'

pod 'JSPatchPlatform'
pod 'JSPatch/Extensions'
pod 'JSPatch/JPCFunction'

pod 'JDStatusBarNotification'

#标准SDK，含IDFA
pod 'UMengAnalytics'
  # Pods for AssistHonest

  target 'AssistHonestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AssistHonestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
